word_list = [
    # Original Z Fighters & Allies
    "goku",
    "vegeta",
    "gohan",
    "trunks",
    "goten",
    "piccolo",
    "krillin",
    "yamcha",
    "bulma",
    "roshi",
    # Z Fighters & Allies (extended)
    "android18",
    "android17",
    "tien",
    "chiaotzu",
    "videl",
    "bardock",
    "raditz",
    "nappa",
    "hercule",
    "beerus",
    "whis",
    # Villains
    "frieza",
    "cell",
    "majinbuu",
    "broly",
    "cooler",
    "zarbon",
    "dodoria",
    "ginyu",
    "jeice",
    "burter",
    "recoome",
    "guldo",
    "babidi",
    "dabura",
    "turles",
    # Super / GT Characters
    "jiren",
    "hit",
    "caulifla",
    "kale",
    "toppo",
    "zamasu",
    "gokublack",
    "cabba",
    "dyspo",
]